"""fix exclude_inbounds_association proxy_id FK to ON DELETE CASCADE

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Branch Labels: None
Depends On: None

"""
from alembic import op
import sqlalchemy as sa


revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    if bind.engine.name == 'mysql':
        # Find and drop the existing FK on proxy_id, then recreate with CASCADE.
        # The constraint name is auto-generated by MySQL (ibfk_2), but may vary
        # across installations, so we look it up dynamically.
        result = bind.execute(sa.text(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "AND TABLE_NAME = 'exclude_inbounds_association' "
            "AND COLUMN_NAME = 'proxy_id' "
            "AND REFERENCED_TABLE_NAME = 'proxies'"
        ))
        row = result.fetchone()
        if row:
            constraint_name = row[0]
            bind.execute(sa.text(
                f"ALTER TABLE exclude_inbounds_association "
                f"DROP FOREIGN KEY `{constraint_name}`"
            ))
        bind.execute(sa.text(
            "ALTER TABLE exclude_inbounds_association "
            "ADD CONSTRAINT excl_inbounds_proxy_fk "
            "FOREIGN KEY (proxy_id) REFERENCES proxies(id) ON DELETE CASCADE"
        ))


def downgrade() -> None:
    bind = op.get_bind()

    if bind.engine.name == 'mysql':
        bind.execute(sa.text(
            "ALTER TABLE exclude_inbounds_association "
            "DROP FOREIGN KEY IF EXISTS excl_inbounds_proxy_fk"
        ))
        bind.execute(sa.text(
            "ALTER TABLE exclude_inbounds_association "
            "ADD CONSTRAINT excl_inbounds_proxy_fk_noaction "
            "FOREIGN KEY (proxy_id) REFERENCES proxies(id)"
        ))
